version: '3.8'

networks:
  micro-lumen-nest:
    external: true

services:
  lumen_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lumen_app
    networks:
      - micro-lumen-nest
    ports:
      - "8001:8001"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db


  db:
    image: mysql:8.0
    container_name: lumen_db
    restart: always
    networks:
      - micro-lumen-nest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
